### ISSUE TITLE
Linux Wine

### ISSUE THREAD

**Issue by ethicalhacker7192** [atampy25/simple-mod-framework#576]
I know you didn't write this for Linux. It would be nice to have a wine port or Linux version. Deploy.exe works. but not the mod manager.

**Comment by supertin** [comment]
I'm same as the OP - Deploy works but mod manager doesn't open. Initially I had deploy telling me to re-read the install instructions, which is hilarious because there aren't any. Trick is to have deploy.exe inside a folder that is within the Hitman 3 folder so that the default config.json path references make sense.

Now, does anyone know exactly what deploy.exe does? Is this what the mod manager users to install the mods? Is there a manual process we can use to bypass the mod manager not working?

Oh, should probably mention I'm running under Proton 7.0 because that's what my Hitman install is running under. Haven't tried mod manager under my system WINE.

**Comment by nonbinary-duck** [comment]
@supertin When you say the deploy exec runs, have you configured it to do anything? I.e. if you were to enable mods in the manager and run deploy, does it do anything?

For me, doing that requires a funky VM setup that thus far has been effective. As for what deploy does, I'm pretty sure it just applies the changes to the game files as defined by the mods.

Also for WINE, I just use Proton experimental running under the hitman prefix and the mod manager works perfectly until it launches deploy to apply changes where I get the same disk letter error.

**Comment by supertin** [comment]
Yeah. Enable mods in the manager, which can't apply them, then run deploy and it works fine.

I ran the Mod Manager under vanilla WINE 8.9 (without any changes to WINEPREFIX - just using the default) cd'ed into the Mod Manager directory. Set up what I wanted, then hit apply and let it fail.

Then I used Proton running as the Hitman 3 prefix to run deploy (to remind myself later - "protontricks 1659040 shell", cd to directory deploy is located in, then "wine deploy.exe")

I only enabled no alerted territories in the rogueless freelancer mod. I'm fairly sure it's working as I don't seem to have an alerted territory in the mission set I just started (2nd set, so it should have 1 I believe). I will enable more and test again tomorrow (getting late here).

**Comment by clemens98** [comment]
"This issue was closed because it was inactive for 5 days since being marked as stale."
so every issue solves itself if not generating any news in 10 days?

**Comment by AnthonyFuller** [comment]
SMF has it's own issues when running in wine. There's no Linux support planned for v2, running it in wine is not an officially supported use case. You have just replied to a nearly year old issue.

**Comment by awsms** [comment]
Is the drag&drop feature broken for you as well? Always makes ModManager.exe crash.
